assembly/        "assembly sample class"
kmod/            "simple kernel module"
kmod_cdev/       "cdev module driver without dts"
kmod_misc/       "misc module driver"
drv_api.c        "api reference"
