#!/bin/bash

PATH_BASE=$(cd `dirname $0`; pwd)
PATH_ROOT=${PATH_BASE}/root_zwscp
PATH_COOKIES=${PATH_BASE}/.cookies/cookies_zwscp

source ${PATH_COOKIES}
source ${PATH_ROOT}/zwscp

########################################################################################################
# 打印用法
########################################################################################################
function print_usage()
{
	echo "usage: zwput <-a/-s/-e/-t> <file>"
}

########################################################################################################
# 程序入口
########################################################################################################
function zwscp_entry()
{
	# 如果是编辑SCP
	if [ $1 = '-edit' ];then
		vi ${PATH_COOKIES}
		exit 1
	fi

	# 打印用法
	if [ $# -lt 2 ];then
		print_uages
		exit 1
	fi

	# 设置PATH_SCP
	set_scp_path $1

	# 拷贝
	scp -r $2 $PATH_SCP
}

zwscp_entry $@

