#!/bin/bash

PATH_BASE=$(cd `dirname $0`; pwd)
PATH_ROOT=${PATH_BASE}/root_zwscp
PATH_COOKIES=${PATH_BASE}/.cookies/cookies_zwscp

source ${PATH_COOKIES}
source ${PATH_ROOT}/zwscp

########################################################################################################
# 程序入口
########################################################################################################
function zwscp_entry()
{
	# 如果没写参数
	if [ $# = 0 ];then
		print_usage
		exit 1
	fi

	# 如果是编辑SCP
	if [ $1 = '-edit' ];then
		vi ${PATH_COOKIES}
		exit 1
	fi

	# 如果只有一个参数
	if [ $# = 1 ];then
		scp -r $2 $PATH_EMBED
		exit 1
	fi

	# 设置PATH_SCP
	set_scp_path $1
	scp -r $2 $PATH_SCP
}

zwscp_entry $@

