#!/bin/bash
########################################################################################################
# 此脚本不要修改
########################################################################################################

# 获取脚本所在目录
PATH_BASE=$(cd `dirname $0`; pwd)
PATH_ROOT=${PATH_BASE}/root_zwsample

# 获取模板CLASS
SAMPLE_CLASS=$(ls -l ${PATH_ROOT} |awk '/^d/ {print $NF}')

########################################################################################################
# 帮助选项
########################################################################################################
function print_usage()
{
	echo "usage : sp <class> <sample>"
	echo ""
	echo "class list:"
	echo ${SAMPLE_CLASS}
	echo ""
	echo "optioin list:"
	echo "-cc    create class     sp -cc <class>"
	echo "-cs    create sample    sp -cs <class> <sample> <describe>"
	echo "-ss    sync sample      sp -ss <clsss> <sample>"
	echo "-ls    list sample      sp -ls <class>"
	echo "-es    edit sample      ps -es <class>"
}


########################################################################################################
# 更新模板
########################################################################################################
function sync_sample()
{
	cp $2 ${PATH_ROOT}/$1 -rf
}

########################################################################################################
# 创建模板
########################################################################################################
function create_class()
{
	mkdir -p ${PATH_ROOT}/$1
	touch ${PATH_ROOT}/$1/note.sp
}

########################################################################################################
# 创建sample
########################################################################################################
function create_sample()
{
	local STR_COUNT
	local KEY
	local INDEX
	local CLASS
	local SAMPLE

	# 初始化变量
	CLASS=$2
	SAMPLE=$3

	# 参数判断
	if [ $# -lt 4 ];then
		echo "create sample arg must > 4"
		exit 1
	fi

	# 计算字符串数量
	STR_COUNT=`expr $# - 3`

	# 拼接模板名称
	KEY+="$SAMPLE \""

	# 拼接字符串
	for i in $(seq $STR_COUNT)
	do
		INDEX=`expr $i + 3`
		eval KEY+=$(echo \${${INDEX}})
		KEY+=' '
	done

	KEY+=\"

	# 创建文件
	cp $SAMPLE ${PATH_ROOT}/$CLASS -rf

	# 添加备注
	echo $KEY >> ${PATH_ROOT}/$CLASS/note.sp
}

########################################################################################################
# 显示模板
########################################################################################################
function list_sample()
{
	local KEY
	local STR
	local CLASS=$2
	local FILE_SP=$PATH_ROOT/$CLASS/note.sp

	# 读取文件
	while read rows
	do
		KEY=`echo $rows | cut -d \" -f 1`
		STR=`echo $rows | cut -d \" -f 2`
		printf "%-10s" $KEY
		echo $STR
	done < $FILE_SP
}


########################################################################################################
# 编辑模板
########################################################################################################
function edit_sample()
{
	local CLASS=$2
	local FILE_SP=$PATH_ROOT/$CLASS/note.sp

	vi $FILE_SP
}

########################################################################################################
# 模板入口
########################################################################################################
function zwsample_entry()
{
	# 如果参数个数小于2, 打印提示
	if [ $# = 0 ];then
    	print_usage $@
		exit 1
	fi

	# 参数判断
	case $1 in
		-h)
		print_usage $@
		;;

		-cc)
		create_class $@
		;;

		-cs)
		create_sample $@
		;;

		-ss)
		sync_sample $@
		;;

		-ls)
		list_sample $@
		;;

		-es)
		edit_sample $@
		;;

		*)
		${PATH_ROOT}/$1/note.i $2
		;;
		
	esac
}

zwsample_entry $@
