#!/bin/bash
########################################################################################################
# 此脚本不要修改
########################################################################################################

# 获取脚本所在目录
PATH_BASE=$(cd `dirname $0`; pwd)
PATH_ROOT=${PATH_BASE}/root_zwsample

# 获取模板CLASS
SAMPLE_CLASS=$(ls -l ${PATH_ROOT} |awk '/^d/ {print $NF}')

########################################################################################################
# 帮助选项
########################################################################################################
function print_usage()
{
	echo "usage : sp <class> <sample>"
	echo ""
	echo "class list:"
	echo ${SAMPLE_CLASS}
	echo ""
	echo "optioin list:"
	echo "-ls    list sample      sp -ls <class>"
	echo "-h     help"
}

########################################################################################################
# 显示模板
########################################################################################################
function list_sample()
{
	local KEY
	local STR
	local CLASS=$2
	local FILE_SP=$PATH_ROOT/$CLASS/note.sp

	# 读取文件
	while read rows
	do
		KEY=`echo $rows | cut -d \" -f 1`
		STR=`echo $rows | cut -d \" -f 2`
		printf "%-20s" $KEY
		echo $STR
	done < $FILE_SP
}

########################################################################################################
# 模板入口
########################################################################################################
function zwsample_entry()
{
	# 如果参数个数小于2, 打印提示
	if [ $# = 0 ];then
    	print_usage $@
		exit 1
	fi

	# 参数判断
	case $1 in
		-h)
		print_usage $@
		;;

		-ls)
		list_sample $@
		;;

		*)
		cp -rf ${PATH_ROOT}/$1/$2 .
		;;
		
	esac
}

zwsample_entry $@
