#!/bin/bash

PATH_BASE=$(cd `dirname $0`; pwd)
PATH_ROOT=${PATH_BASE}/root_zwscp
PATH_COOKIES=${PATH_BASE}/.cookies/cookies_zwscp

source ${PATH_COOKIES}
source ${PATH_ROOT}/zwscp

########################################################################################################
# 程序入口
########################################################################################################
function zwscp_entry()
{
	# 如果没写参数
	if [ $# = 0 ];then
		ssh root@120.48.82.24
		exit 1
	fi

	# 或帮助命令, 则打印帮助信息
	if [ $1 = '-h' ] || [ $1 = '--help' ];then
		print_usage
		exit 1
	fi

	# 设置SCP路径
	set_scp_path $@

	# 从SCP中提取SSH路径
	arr=(`echo $PATH_SCP | tr ':' ' '`)
	ssh ${arr[0]}
}

zwscp_entry $@

