#!/bin/bash

PATH_BASE=$(cd `dirname $0`; pwd)
PATH_ROOT=${PATH_BASE}/root_zwscp
PATH_COOKIES=${PATH_BASE}/.cookies/cookies_zwscp

source ${PATH_COOKIES}
source ${PATH_ROOT}/zwscp

########################################################################################################
# 打印用法
########################################################################################################
function print_usage()
{
	echo "usage: zwget <-a/-s/-e/-t> <file>"
}

########################################################################################################
# 程序入口
########################################################################################################
function zwscp_entry()
{
     # 如果是编辑SCP
     if [ $1 = '-edit' ];then
        vi ${PATH_COOKIES}
        exit 1
     fi

	 case $1 in
	 	-e)
		ssh zli@10.1.3.15
		;;

		-t0)
		ssh kylin@10.10.10.181
		;;

		-t1)
		ssh kylin@10.10.10.182
		;;

	esac
}

zwscp_entry $@

