#!/bin/bash

PATH_BASE=$(cd `dirname $0`; pwd)

########################################################################################################
# 打印使用方法
########################################################################################################
function print_usage()
{
    echo "cmd           abbr   description"
    echo "----------    ----   --------------------"
    echo "zwput         pt     put file to ssh"
    echo "zwget         gt     get file from ssh"
    echo "zwssh         zsh    ssh"
    echo "zwsample      sp     get sample file"
    echo "zwstr         str    str deal tool"
    echo "zwtrace       zt     ftrace tool"
    echo "zwcd          zd     path tool"
    echo "zwweb         wb     zw web manage tool"
}

########################################################################################################
# 别名初始化
########################################################################################################
function alias_init()
{
    ln -s $PATH_BASE/zwput $PATH_BASE/pt 2> /dev/null
    ln -s $PATH_BASE/zwget $PATH_BASE/gt 2> /dev/null
    ln -s $PATH_BASE/zwsample $PATH_BASE/sp 2> /dev/null
    ln -s $PATH_BASE/zwssh $PATH_BASE/zsh 2> /dev/null
    ln -s $PATH_BASE/zwweb $PATH_BASE/wb 2> /dev/null
}

########################################################################################################
# 文件初始化
########################################################################################################
function file_init()
{
    # 创建cookies文件夹
    mkdir -p $PATH_BASE/.cookies

    # 初始化scp
    if [ ! -e $PATH_BASE/.cookies/cookies_zwscp ]; then
        cp $PATH_BASE/root_zwsample/zwtools/sample_scp $PATH_BASE/.cookies/cookies_zwscp
    fi

	# 初始化zwcd
	if [ ! -e $PATH_BASE/.cookies_zwcd/zd_list ]; then
		mkdir -p $PATH_BASE/.cookies_zwcd
		touch $PATH_BASE/.cookies_zwcd/zd_list
	fi
}

########################################################################################################
# 工具初始化
########################################################################################################
function zwtool_init()
{
    alias_init
    file_init
}

########################################################################################################
# 程序入口
########################################################################################################
function zwtool_entry()
{
	# 如果没写参数
	if [ $# = 0 ];then
		print_usage
		exit 1
	fi

	case $1 in
        -edit)
        vi ${PATH_BASE}/zwtool
        ;;

		-init)
		zwtool_init
		;;

		*)
		print_usage
		;;
	esac    
}

zwtool_entry $@
