#!/bin/bash

PATH_BASE=$(cd `dirname $0`; pwd)

########################################################################################################
# 打印使用方法
########################################################################################################
function print_usage()
{
    echo "cmd           abbr   description"
    echo "----------    ----   --------------------"
    echo "zwput         pt     put file to ssh"
    echo "zwget         gt     get file from ssh"
    echo "zwssh                ssh"
    echo "zwsample      sp     get sample file"
    echo "zwstr         str    str deal tool"
    echo "zwtrace       zt     ftrace tool"
    echo "zwpath        zp     path tool"
}

########################################################################################################
# 别名初始化
########################################################################################################
function alias_init()
{
    ln -s $PATH_BASE/zwput $PATH_BASE/pt 2> /dev/null
    ln -s $PATH_BASE/zwget $PATH_BASE/gt 2> /dev/null
    ln -s $PATH_BASE/zwsample $PATH_BASE/sp 2> /dev/null
}

########################################################################################################
# 工具初始化
########################################################################################################
function zwtool_init()
{
    alias_init
}

########################################################################################################
# 程序入口
########################################################################################################
function zwtool_entry()
{
	# 如果没写参数
	if [ $# = 0 ];then
		print_usage
		exit 1
	fi

	case $1 in
		-init)
		zwtool_init
		;;

		*)
		print_usage
		;;
	esac    
}

zwtool_entry $@
