#!/bin/bash

# 待定参数
PATH_SCP=

function set_scp_path()
{
	case $1 in
		-a)
		PATH_SCP=$PATH_ZW/$2
		;;

		-s)
		PATH_SCP=$PATH_SERVE/$2
		;;

		-e)
		PATH_SCP=$PATH_EMBED/$2
		;;

		-t)
		PATH_SCP=$PATH_TMP/$2
		;;

		*)
		;;
	esac
}

