#!/bin/bash

# 待定参数
PATH_SCP=
PATH_ZW=root@120.48.82.24:/root/share

########################################################################################################
# 打印用法
########################################################################################################
function print_usage()
{
	echo "usage: zt/pt/zwssh <option>"
	echo ""
	echo "option:"
	echo "-a    my server"
	echo "-s    company server"
	echo "-e    company board(default)"
	echo "-t    tmp"
}

########################################################################################################
# 设置SCP地址
########################################################################################################
function set_scp_path()
{
	case $1 in
		-a)
		PATH_SCP=$PATH_ZW/$2
		;;

		-s)
		PATH_SCP=$PATH_SERVE/$2
		;;

		-e)
		PATH_SCP=$PATH_EMBED/$2
		;;

		-u)
		PATH_SCP=$PATH_UBUNTU/$2
		;;

		-t)
		PATH_SCP=$PATH_TMP/$2
		;;

		*)
		print_usage
		;;
	esac
}

